# Generated by Django 2.2.4 on 2019-08-22 03:26

import autoslug.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, verbose_name='Title')),
                ('slug', autoslug.fields.AutoSlugField(blank=True, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Editing required', 'Editing required'), ('Ready to publish', 'Ready to publish'), ('Proofreading required', 'Proofreading required'), ('Published', 'Published')], db_index=True, default='Draft', max_length=255, verbose_name='Status')),
                ('publication_date', models.DateTimeField(db_index=True, default=datetime.datetime.now, verbose_name='Publication date')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('last_modified_date', models.DateTimeField(auto_now=True, verbose_name='Last modified date')),
                ('is_hidden', models.BooleanField(db_index=True, default=False, verbose_name='Is hidden')),
                ('token', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, verbose_name='Token')),
                ('content', models.TextField(verbose_name='Content')),
                ('owner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
            },
        ),
    ]
